"""dynamic salt

Revision ID: 0da065593a69
Revises: e4d5ccc6ec42
Create Date: 2024-06-11 22:44:11.206382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0da065593a69'
down_revision: Union[str, None] = 'e4d5ccc6ec42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dynamic_salt', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dynamic_salt')
    # ### end Alembic commands ###
